### ISSUE TITLE
unexpected token in "lakefile.lean"

### ISSUE THREAD

**Issue by isaac-mackey** [leanprover-community/mathlib4#17177]
In "lakefile.lean"

import Lake

open Lake DSL

/-!
## Mathlib dependencies on upstream projects
-/

require "leanprover-community" / "batteries" @ git "main"
require "leanprover-community" / "Qq" @ git "master"
require "leanprover-community" / "aesop" @ git "master"
require "leanprover-community" / "proofwidgets" @ git "v0.0.42"
require "leanprover-community" / "importGraph" @ git "main"
require "leanprover-community" / "LeanSearchClient" @ git "main"
  from git "https://github.com/leanprover-community/LeanSearchClient" @ "main"
  
Yields error
  
  lakefile.lean:10:7
unexpected token; expected identifier

**Comment by isaac-mackey** [comment]
resolved with update to batteries library

**Comment by digama0** [comment]
This error means you have an outdated version of lake. The easiest way to fix it is to manually copy the lean-toolchain from mathlib or batteries via `cp .lake/packages/mathlib/lean-toolchain .` from your project root. (We're aware this issue and the fix is not obvious and are working toward a more automatic solution.)
