### ISSUE TITLE
PGame.Short is defined incorrectly

### ISSUE THREAD

**Issue by LeoDog896** [leanprover-community/mathlib4#20275]
Short games have finitely many moves up to equivalence. However, `PGame.Short` is only considered finite at the type level. [Playground](https://live.lean-lang.org/#codez=JYWwDg9gTgLgBAWQIYwBYBtgCMB0BlAUxgBVUDoBPHAcSRAJwAVb6AoUSWRFDbfI0uShUWDPKmgx24SdzSZchEmUo06DAELBYqACZIK0zvGTy+SwaoDyUXcAB2SdDg1IAzsADGR2ad64AERQkHAAxBxgKME13Lx8uPwUcIJgQ8PtI6JwAYSRbVlZHejcwJE8COAsVYQKIaPs4N086gl04ADkUAFcoJyswNzhmdQLdAgAzRtSoAEk3VDgALiHRJYBeOEAL8kBUQgAaOD24ca6GgH04NYA+OAAGfeOzi+ubwEvyAoABAG0PcABdODQQgIICmeTmqFO6AmMAQEAAbgRBss3NNwTgADLQ2EIwYbbbrOBQcboVhfH5gf6A6DA0GzeanKDAADmqBh8MRS1paIASszWdiOXiCUSSaTvhxKdUaSiwfSQOzMeN4AAPTkyumoHDyhGKlUXW7C4li8mSoEg9Xg07agi8ll65Go+Za9m21lwVUbG6G0UAWh9cAAojKsJh5gDUChaadgE6sNo0PoKPqAIysKlQaXTaP0uM6RNqx2a3MJgwpglYJNQADucE+w3oOGLegMpzG41+AG5GhwCn64ABNIj7YDwGP2ADk8HEkjTUpB9ggMFOFvp81kyzmAfAkTgAAp62IJFwV6gAJTlwxwQk1z4xrdgSLR8bt1hXiJQCBwVCvuCedwc78ryQLA3B6NoHBRGZ7HGBwRwITopCvck4Agex0CTT4FyXBwYPsOCn3GU5cLg/Z0jgnAIEI3DMgqU5fgKAh7DaKohAoIA).

Any game with a birthday less than `Ordinal.omega0` should be necessarily short, as a game with infinitely many moves up to equivalence would have to exhaust the list of finite birthdays since there are only a finite amount of games per birthday. However, the playground link above provides an explicit counterexample.

Inlined playground:

```lean4
import Mathlib.SetTheory.Game.PGame
import Mathlib.SetTheory.Game.Short
import Mathlib.SetTheory.Game.Birthday
import Mathlib.SetTheory.Ordinal.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Fintype.Card

namespace SetTheory

open scoped NaturalOps PGame

def starIsh : PGame := ⟨ℕ, ℕ, fun _ => 0, fun _ => 0⟩

@[simp] theorem starIsh_leftMoves : starIsh.LeftMoves = ℕ := rfl
@[simp] theorem starIsh_rightMoves : starIsh.RightMoves = ℕ := rfl

@[simp] theorem starIsh_moveLeft x : starIsh.moveLeft x = 0 := rfl
@[simp] theorem starIsh_moveRight x : starIsh.moveRight x = 0 := rfl

-- Establish that star_ish.birthday = 1
theorem star_ish_birthday : starIsh.birthday = 1 := by rw [PGame.birthday_def]; simp

-- Yet, it isn't Short
theorem not_starIsh_short : IsEmpty (PGame.Short starIsh) := by
  rw [isEmpty_iff]
  intro h
  cases h
  absurd instInfiniteNat
  simp only [not_infinite_iff_finite, Finite.of_fintype _]

end SetTheory
```

**Comment by trivial1711** [comment]
I posted this on Zulip already (https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/.5BPGame.5D.20Short.20is.20wrong/near/491053628); I will repeat it here.

Consider this pregame from your example.
```
def starIsh : PGame := ⟨ℕ, ℕ, fun _ => 0, fun _ => 0⟩
```
You say that this should be considered short, because even though there are infinitely many left options, they are all equal to each other. However, this argument relies on the statement that `0 = 0`, which is an equality of pregames. There is a reason that no definitions currently in mathlib, as far as I know, refer to equality of pregames; it is an "evil" notion (https://nforum.ncatlab.org/discussion/3616/evil/) and can cause many innocuous statements to become unprovable ([#**new members>Newbie question : Equality of Types**](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Equality.20with.20Types)). So, maybe the definition in mathlib is correct, and this game shouldn't be considered short.

**Comment by trivial1711** [comment]
Overall, it is expected that some definitions will have to be slightly changed from Conway's book, both because Conway never formally defined a "pregame" and because he was working from different foundations. Given that, I think the definition of "short pregame" currently in mathlib is very sensible. I would, however, agree with changing the docstrings to make some of these issues more clear.
