### ISSUE TITLE
`max`/`min`

### ISSUE THREAD

**Issue by gebner** [leanprover-community/mathlib4#369]
From #348: Lean 4 defines `max` and `min` in the prelude, while Lean 3 (as of https://github.com/leanprover-community/lean/pull/609) defines them differently as part of `linear_order`. We will need to figure out how to resolve this conflict.

Probably the easiest thing would be to get notation typeclasses `Max` and `Min` into core.

**Comment by dwrensha** [comment]
The problem is that there's a bunch of uses of `min` and `max` in mathlib3 and they all mean `linear_order.min` or `linear_order.max`. If we directly translate that stuff to mathlib4 (and we keep the current prelude) then we'll need to fully specify  `LinearOrder.min` and `LinearOrder.max` everywhere to avoid using the prelude definitions. That seems like it will invite confusing errors.

> Probably the easiest thing would be to get notation typeclasses Max and Min into core.

@gebner I don't follow how that would help. Would the `LinearOrder` typeclass then extend `Min` and `Max` and override the definitions? Would we need to be worried about overlapping instances?

**Comment by gebner** [comment]
Yes, `LinearOrder` should extend `Min` and `Max` (just as it extends `LE`).  The rules for overlapping instances are the same as for `LE`: all definitions of `≤` for a type need to be defeq.

**Comment by gebner** [comment]
Fixed by https://github.com/leanprover/lean4/pull/1765

We just need to add `extends Max` and `Min` to `LinearOrder` tomorrow.
