### ISSUE TITLE
Fix FieldTheory.RatFunc

### ISSUE THREAD

**Issue by urkud** [leanprover-community/mathlib4#4513]
In the original file, sometimes `K` is a field and sometimes `K` is a
commutative ring (optionally, a domain). In some sections, this was
incorrectly translated to Lean 4 in #4293. This blocks #4512

**Comment by adomani** [comment]
Yuri, I already had some suspicions that something like this could be happening, and I had a PR with a beginning of a cleanup:  #4373.

Naïvely, I just trusted that Lean would pick up the right combination of typeclasses, without having to check it, but it seems that I was wrong.

Still, this is very laborious to check by hand, since in the local context you always have all the available variables, and only after elaboration, the final declaration looses the "irrelevant" ones.  So, my approach would be to `#print` every theorem and check that it got the right typeclasses...  Maybe this could be automated, flagging a discrepancy with mathlib3, when there is one?

**Comment by adomani** [comment]
Let me also ping @eric-wieser and @Vierkantor, since they were also in the loop for these issues.

**Comment by eric-wieser** [comment]
Maybe it would be reasonable to refactor this in mathlib3 to use `section`s, and then re-port the file from scratch?

**Comment by adomani** [comment]
Eric, you are probably right.  I find this issue of auto-include/omit more subtle than the autoImplicit ones.  Is it possible to disable it?

**Comment by eric-wieser** [comment]
No, I don't think so. The exact behavior as I understand it is "all the variables that exist are available inside the proof, but the ones you don't use are removed automatically"

**Comment by adomani** [comment]
I started on branch#adomani_section_ratfunc but won't have time to finish in a few hours.

**Comment by adomani** [comment]
I finished the sectioning of `field_theory/ratfunc`: #19133.

On my computer, the file `field_theory.laurent` works with the sectioning made.  Let's wait to see if CI is happy with the rest of the files.

**Comment by adomani** [comment]
An update: @Vierkantor approved the mathlib3 PR.

Once it merges, I'll prepare the matching mathlib4 port of `RatFunc` and hopefully this will fix Yuri's porting problems!

**Comment by adomani** [comment]
#4580 passes CI, I merged it into Yuri's PR and it builds locally and passed the building step of CI.  It's all looking good!

**Comment by adomani** [comment]
@urkud, I'm guessing that this issue can now be closed, right?

**Comment by urkud** [comment]
Yes, indeed. I guess, it was not auto closed because Github doesn't know that your PR was merged, not discarded.

**Comment by adomani** [comment]
Probably, but the other PR did autoclose!
